[package]
name = "tracert"
version = "0.1.0"
authors = ["bnlrnz <bnlrnz@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
[dependencies.pnet]
version = "0.27.2"